version: '3'
services:
  app:
    build: ./
    container_name: app
    tty: true
    entrypoint: dockerize -template ./.docker/app/.env.build:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    environment:
      DB_HOST: db
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - .:/var/www
    depends_on:
      - db
      - redis
    networks:
      - app-network
  db:
    image: mysql:5.7.22
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./.docker/dbdata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
  nginx:
    build: ./.docker/nginx
    container_name: nginx
    restart: always
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    depends_on:
      - app
    networks:
      - app-network
  redis:
    image: redis:alpine
    container_name: redis
    expose:
      - 6379
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
